// <auto-generated />
using System;
using BookStoreMy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStoreMy.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20221107073314_LanguageModelAdded")]
    partial class LanguageModelAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BookStoreMy.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalPages")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Vasil",
                            Category = "Programming",
                            Description = "BlaBla",
                            Language = "Georgian",
                            Title = "C#",
                            TotalPages = 400
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nitish",
                            Category = "It",
                            Description = "BlaBla",
                            Language = "English",
                            Title = "Java",
                            TotalPages = 600
                        });
                });

            modelBuilder.Entity("BookStoreMy.Models.LanguageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Hindi"
                        },
                        new
                        {
                            Id = 2,
                            Text = "English"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Georgian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
